name: dropdon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.36.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: bogi
      fonts:
        - asset: fonts/Boogie.otf
    - family: mountain
      fonts:
        - asset: fonts/MountainKingRegular.ttf